  target_sources(
          obs-studio
          PRIVATE
          auth/OAuthManager.cpp
          auth/OAuthManager.hpp
          auth/SPTServiceManager.cpp
          auth/SPTServiceManager.hpp
          auth/SPTAPIServices.cpp
          auth/SPTAPIServices.hpp
  )